import {reliableCommands,audioStore} from './classroom-reliable.js?v=20261006-stable2';
import {createCompletion} from './classroom-completion.js?v=20261007-peer1';
const $=id=>document.getElementById(id),params=new URL(location.href).searchParams,normal=document.documentElement.dataset.student==='authenticated',host=!normal&&params.get('role')==='teacher',base=normal?'https://zhuyin-api.j822925.workers.dev/trial/classroom-api':'/trial/classroom-api';
let studentSession=null,studentIdentity=null,classId='main',homeUrl='https://j822925.github.io/zhuyin-game-new/';
if(normal){
 const [{createStudentSession},{classStorageKey,classUrl,currentClass}]=await Promise.all([import('./student-session.js'),import('./class-context.js?v=20260928-all1')]);
 classId=currentClass;homeUrl=classUrl('./');studentSession=createStudentSession({storage:sessionStorage,key:classStorageKey('zhuyin.student-session.v1:'+new URL('.',location.href).pathname+':live')});studentIdentity=studentSession.read();
 document.querySelector('header a.home').href=homeUrl;document.querySelector('header a.home').textContent='🏡 回首頁';
 document.querySelector('.notice').textContent='🌟 全班問答・用平常的帳號加入本班活動，不必重填座號或密碼。完成活動可依名次領星星，不計入正式小考成績。';
}else if(host&&params.get('from')==='admin'){
 document.querySelector('header a.home').href='/admin/?class='+encodeURIComponent(params.get('class')||'main');document.querySelector('header a.home').textContent='🏡 回教師後台';
 document.querySelector('.notice').textContent='🌟 全班問答試用・孩子正常登入遊戲後，按「加入全班問答」就能加入本班活動。完成活動依名次發星星，不計入正式小考成績。';
}
const messages={peer_unsupported:'這個瀏覽器不支援直連。老師請用 Chrome／Edge；iPad 請更新系統後用 Safari。',peer_connection_failed:'無法直連老師電腦，請確認 Wi-Fi／VPN 並請老師重新開放 P2P 連線。',peer_not_available:'P2P 試玩暫時無法使用，原本雲端模式仍保留。',host_not_connected:'老師尚未開放 P2P 配對，請老師按重新開放連線。',classroom_quota_exceeded:'雲端今日的免費連線額度已用完，台灣時間每天早上 8 點重置。暫時無法開始全班問答；一般單人練習仍可使用。',login_required:'登入已到期，請回首頁重新選座號、輸入密碼。',class_room_mismatch:'這不是本班的活動，請重新讀取活動清單。',admin_required:'請先登入老師 Google 帳號。',teacher_forbidden:'這個 Google 帳號沒有老師權限。',room_missing:'找不到這個活動，請確認老師還開著活動。',seat_taken:'這個座號已有人使用。若不是你，請找老師確認；同一台裝置可恢復原座號。',room_full:'房間已滿，最多 32 位孩子。',already_started:'活動已開始，請等老師開下一場。',scope_small:'範圍不足，至少需要 4 個可出題項目。',invalid_settings:'請檢查名稱、範圍、題數與時間。',not_ready:'還有孩子沒有準備好。',not_heard:'還有孩子沒有聽完題目。',stale_state:'畫面剛有更新，請再按一次。',wrong_phase:'老師已切換階段，請看目前畫面。',invalid_seat:'請輸入正確座號。',capacity:'測試房間已滿，請先關閉不用的房間。',host_room_limit:'每位老師同時最多兩個測試房間，請先結束舊房間。',slow_down:'操作太快了，請稍等再試。',room_closed:'老師已關閉房間。'};
Object.assign(messages,{peer_checkpoint_missing:'這台電腦沒有本場的作答進度。請回到原本主持的分頁；若已遺失，請結束舊活動並建立新活動。',peer_players_not_connected:'還有孩子沒有連好，請等全部直連成功再開始／繼續。'});
let transport=host&&params.get('transport')==='peer'?'peer':'cloud';let teacher=null,auth=null,state=null,socket=null,code='',seat='',offset=0,audioKey='',pendingAnswer=null,stopped=false,retry=0,heartbeat=null,lastPong=0,reconnectTimer=null,generation=0,connecting=null,firstStateTimer=null,preparing=false,prepared=0,prepareTotal=0,playGeneration=0,teacherMediaCode='',teacherAudioDone='';
const audio=new Audio();audio.preload='auto';let armed=false;
const completion=createCompletion({document,rankTable}),sounds=audioStore();
const commands=reliableCommands({getState:()=>state,getSocket:()=>socket,onChange:()=>{pendingAnswer=commands.answer()?{key:code+':'+commands.answer().index,value:commands.answer().value}:null;if(state)render();},onError:error,storage:sessionStorage,key:'zhuyin.classroom.pending.'+(host?'teacher':classId+':'+(studentIdentity?.seat||'guest'))});commands.start();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const terminal=new Set(['classroom_quota_exceeded','login_required','admin_required','teacher_forbidden','forbidden','class_room_mismatch','room_missing','room_closed','seat_taken','not_joined','already_started']);
terminal.add('peer_checkpoint_missing');
const el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
function message(text){$('message').textContent=text||'';}
function error(e){message(messages[e.message]|| (e.code?.includes('popup')?'登入視窗無法開啟。請用 Safari／Chrome 直接開啟，允許彈出視窗後再試。':'暫時無法完成，請確認網路後再試一次。'));}
async function api(path,data={},teacherOnly=false){
 for(let attempt=0;attempt<3;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);
 try{const r=await fetch(base+path,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json',...(normal?{Authorization:'Bearer '+currentStudent().token}:{}),...(teacherOnly?{Authorization:'Bearer '+await teacher.getIdToken()}: {})},body:JSON.stringify(normal?{...data,classId}:data),signal:controller.signal});let out;try{out=await r.json();}catch{throw Error('network');}
 if(!r.ok||out.error){const e=Error(out.error||'network');e.transient=r.status===429||r.status>=500;e.retryAfterMs=out.retryAfterMs;throw e;}return out;
 }catch(e){if(terminal.has(e.message)||e.transient===false||attempt===2)throw e;await sleep(e.retryAfterMs?Math.min(15000,e.retryAfterMs):500+Math.random()*500+attempt*750);}finally{clearTimeout(timer);}}
}
async function unlock(){if(armed)return;try{audio.src='data:audio/wav;base64,UklGRiYAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQIAAACAgA==';await audio.play();audio.pause();armed=true;}catch{}}
function currentStudent(){const current=studentSession?.read();if(!current||current.token!==studentIdentity?.token||current.seat!==studentIdentity?.seat)throw Error('login_required');return current;}
let device;try{device=localStorage.getItem('zhuyin.classroom.device');if(!device){device=crypto.randomUUID();localStorage.setItem('zhuyin.classroom.device',device);}}catch{device=crypto.randomUUID();}
function memo(){try{sessionStorage.setItem('zhuyin.classroom.join',JSON.stringify({code,seat}));}catch{}}
$('teacher-entry').hidden=!host;$('student-entry').hidden=host;if(!host&&!normal&&!params.get('room')){$('join-form').hidden=true;$('student-login-link').hidden=false;}if(params.get('room'))$('room-code').value=params.get('room');
try{const old=JSON.parse(sessionStorage.getItem('zhuyin.classroom.join'));if(old&&!host&&!normal&&params.get('room')){if(!$('room-code').value)$('room-code').value=old.code;$('seat').value=old.seat;}}catch{}
function button(label,fn){const b=el('button',label);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){error(e);}finally{b.disabled=false;}};return b;}
async function hostRooms(){const [cloud,peer]=await Promise.all([api('/hosts',{},true),api('/peer/hosts',{},true).catch(()=>({rooms:[]}))]);const out={rooms:[...cloud.rooms,...peer.rooms]};$('host-rooms').replaceChildren();for(const r of out.rooms)$('host-rooms').append(button((r.transport==='peer'?'🖥️ P2P 試玩・':'繼續主持・')+r.title,async()=>{await unlock();transport=r.transport||'cloud';code=r.code;stopped=false;await connect();}));if(!out.rooms.length)$('host-rooms').textContent='目前沒有進行中的房間。';}
async function taught(){const cid=$('class-id').value,r=await fetch('/api?api=config&class='+encodeURIComponent(cid),{cache:'no-store'}),c=await r.json(),selected=new Set([...(c.symbols||[]),...(c.compounds||[])]);for(const box of $('scope').querySelectorAll('input'))box.checked=selected.has(box.value);}
let teacherSDK;
// Student tablets do not need to download the Google sign-in library.
if(host)teacherSDK=import('/admin/auth-sdk.js');
$('teacher-login').onclick=async()=>{const b=$('teacher-login');b.disabled=true;message('');try{const {initializeApp,initializeAuth,inMemoryPersistence,browserPopupRedirectResolver,GoogleAuthProvider,signInWithPopup}=await teacherSDK;if(!auth){const c=await(await fetch('/admin/auth-config',{cache:'no-store'})).json();if(c.mode!=='firebase')throw Error('not_configured');auth=initializeAuth(initializeApp(c.firebase,'classroom-quiz'),{persistence:inMemoryPersistence,popupRedirectResolver:browserPopupRedirectResolver});}teacher=(await signInWithPopup(auth,new GoogleAuthProvider())).user;const out=await api('/classes',{},true);$('class-id').replaceChildren();for(const c of out.classes){const opt=el('option',c.name);opt.value=c.id;$('class-id').append(opt);} $('scope').replaceChildren();for(const value of [...out.base,...out.compounds]){const label=el('label'),input=el('input');input.type='checkbox';input.value=value;label.append(input,el('span',value));$('scope').append(label);}if([...$('class-id').options].some(c=>c.value===params.get('class')))$('class-id').value=params.get('class');await taught();$('setup').hidden=false;b.hidden=true;await hostRooms();message('老師登入成功。全班問答完成後依名次發星星，不更動學生帳號或正式小考成績；答錯題目會記在本班教師後台。');}catch(e){error(e);}finally{b.disabled=false;}};
$('class-id').onchange=()=>taught().catch(error);$('taught').onclick=()=>taught().catch(error);for(const [id,checked]of [['all',true],['none',false]])$(id).onclick=()=>{$('scope').querySelectorAll('input').forEach(e=>e.checked=checked);};
$('transport').value=transport;$('transport').onchange=()=>{transport=$('transport').value;$('audio-mode').disabled=transport==='peer';if(transport==='peer')$('audio-mode').value='teacher';};$('transport').onchange();
$('create-form').onsubmit=async e=>{e.preventDefault();$('create').disabled=true;try{await unlock();transport=$('transport').value;if(transport==='peer'&&!globalThis.RTCPeerConnection)throw Error('peer_unsupported');const out=await api(transport==='peer'?'/peer/create':'/create',{createId:crypto.randomUUID(),authenticated:params.get('guest')!=='1',scoring:$('scoring').value,audioMode:$('audio-mode').value,classId:$('class-id').value,title:$('title').value,mode:$('mode').value,count:Number($('count').value),seconds:Number($('seconds').value),symbols:[...$('scope').querySelectorAll('input:checked')].map(e=>e.value)},true);code=out.code;stopped=false;await openSocket(out.ticket,out);}catch(e){error(e);}finally{$('create').disabled=false;}};
$('join-form').onsubmit=async e=>{e.preventDefault();$('join').disabled=true;try{await unlock();code=$('room-code').value.trim();seat=$('seat').value.trim().padStart(2,'0');stopped=false;await connect();memo();}catch(e){error(e);}finally{$('join').disabled=false;}};
async function connect(){
 if(connecting)return connecting;
 connecting=(async()=>{try{const out=host?await api(transport==='peer'?'/peer/host':'/host',{code},true):await api(transport==='peer'?'/peer/student-join':normal?'/student-join':'/join',{code,seat,device});if(stopped)return;if(out.seat)seat=out.seat;commands.restore(code);await openSocket(out.ticket,out);}catch(e){if(terminal.has(e.message)){stopped=true;disable();}error(e);scheduleReconnect();throw e;}finally{connecting=null;}})();return connecting;
}
function scheduleReconnect(){clearTimeout(reconnectTimer);if(transport==='peer'&&retry>=2){$('reconnect').hidden=false;$('connection').textContent='🟠 無法直連，請老師重新開放連線並確認 Wi-Fi／VPN';return;}$('reconnect').hidden=stopped;if(stopped||!code||document.hidden||navigator.onLine===false)return;$('connection').textContent='🟠 網路暫斷，正在自動重連…';reconnectTimer=setTimeout(()=>connect().catch(()=>{}),Math.min(15000,1000*2**Math.min(4,retry++))+Math.random()*500);}
async function openSocket(ticket,info){const gen=++generation;if(socket){socket.onclose=null;socket.close();}clearInterval(heartbeat);clearTimeout(firstStateTimer);clearTimeout(reconnectTimer);$('connection').textContent='正在連線…';const u=new URL(base+'/socket',location.href);u.protocol=u.protocol==='https:'?'wss:':'ws:';let ws;if(transport==='peer'){const {directClassroomSocket}=await import('./classroom-peer.js?v=20261007-peer1');if(gen!==generation)return;ws=socket=directClassroomSocket({host,info:{...info,device},base,api,onStatus:peerStatus});}else ws=socket=new WebSocket(u);
 firstStateTimer=setTimeout(()=>{if(gen===generation)ws.close();},transport==='peer'?30000:15000);
 ws.onopen=()=>{if(gen!==generation)return;ws.send(JSON.stringify({type:'auth',ticket}));lastPong=Date.now();if(transport==='peer')return;heartbeat=setInterval(()=>{if(ws.readyState!==1)return;if(Date.now()-lastPong>30000){ws.close();return;}ws.send('ping');},10000);};
 ws.onmessage=event=>{if(gen!==generation)return;lastPong=Date.now();if(event.data==='pong')return;let d;try{d=JSON.parse(event.data);}catch{return;}
 if(d.type==='state'){clearTimeout(firstStateTimer);if(state?.code===d.state.code&&d.state.version<state.version)return;if(state?.code===d.state.code&&state.phase==='finished'&&d.state.phase==='closed')return;state=d.state;offset=state.serverNow-Date.now();retry=0;commands.state(state);pendingAnswer=commands.answer()?{key:code+':'+commands.answer().index,value:commands.answer().value}:null;$('connection').textContent=transport==='peer'?'🟢 P2P 直連・由老師電腦處理作答':'🟢 已連線';$('reconnect').hidden=true;$('entrance').hidden=true;$('room').hidden=false;render();}
 if(d.type==='ack')commands.receive(d);
 if(d.type==='error'){if(d.id)commands.receive(d);else error(Error(d.error));if(terminal.has(d.error)){stopped=true;disable();ws.close();}}
 if(d.type==='closed'||d.type==='replaced'){stopped=true;message(d.type==='closed'?'老師已結束房間。請回首頁，或重新整理加入下一場。':'這個座號／主持頁已在另一個分頁接手。');disable();}
 };
 ws.onclose=()=>{if(gen!==generation)return;clearInterval(heartbeat);clearTimeout(firstStateTimer);disable();$('connection').textContent='🟠 連線中斷';scheduleReconnect();};
 ws.onerror=()=>{$('connection').textContent='🟠 正在檢查連線…';};
}
function peerStatus(status){const row=$('peer-status');if(row)row.textContent=({peer_waiting:'🖥️ 老師電腦已準備好，等平板建立直連。',peer_connected:'🟢 已直接連到老師電腦。',peer_connection_failed:'⚠ 無法直接連線。請確認學校 Wi-Fi／VPN，老師可按「重新開放 P2P 連線」。不會改用付費中繼。',peer_signal_lost:'⚠ 配對連線已中斷；已直連的平板仍可答題。要重新加入，請老師重新開放 P2P 連線。',peer_summary_saved:'✅ 試玩成績摘要已同步；不發星星、不寫正式錯題紀錄。',peer_summary_pending:'⚠ 試玩摘要尚未同步；請下載本場 CSV 留存，也可以重傳。',peer_metadata_pending:'⚠ 活動狀態尚未同步；已直連的學生仍可正常作答。',host_not_connected:'⚠ 老師尚未開放配對，請老師按「重新開放 P2P 連線」。'})[status]||row.textContent;}
function disable(){if(state?.phase==='finished')return;$('choices').querySelectorAll('button').forEach(b=>b.disabled=true);$('controls').querySelectorAll('button').forEach(b=>b.disabled=true);audio.pause();}
function send(kind,more={}){return commands.submit(kind,more);}
async function play(){if(!state?.question||!host&&state.audioMode==='teacher')return;const gen=++playGeneration,key=code+':'+state.index,url=state.question.audio;audio.pause();$('audio-status').textContent='🎧 正在讀取聲音…';
 try{const local=await sounds.load(url);if(gen!==playGeneration||!state||key!==code+':'+state.index)return;audio.src=local;
 audio.onended=()=>{if(state&&key===code+':'+state.index){teacherAudioDone=key;$('audio-status').textContent='聽完了，可以再聽一次。';if(!host&&state.phase==='listening')send('heard');}};
 audio.onerror=()=>{$('audio-status').textContent='聲音尚未讀取成功，請按「聽題目」重試，或告訴老師。';};
 await audio.play();$('audio-status').textContent='🔊 正在播放…';
 }catch{$('audio-status').textContent='請點上面的喇叭重試；若仍聽不到，請告訴老師。';}}
$('listen').onclick=()=>play();
async function prepare(){if(preparing)return;preparing=true;prepared=0;const media=state?.media||[],activity=code;prepareTotal=media.length;render();try{
 await sleep(Math.random()*400);
 for(const url of media){if(activity!==code)throw Error('changed');await sounds.load(url);prepared++;if(state)render();}
 if(activity===code)send('ready');
 }catch{message('部分聲音還沒下載好，請確認網路後再按「準備好了」。');}finally{preparing=false;if(state)render();}}

async function prepareTeacherAudio(){const activity=code;preparing=true;prepared=0;prepareTotal=state.media.length;try{for(const url of state.media){await sounds.load(url);if(activity!==code)return;prepared++;render();}}catch{message('老師端有聲音尚未下載完成，可以先開始；聽不到時請按喇叭重試。');}finally{preparing=false;if(activity===code)render();}}
function hostControl(label,kind,more={}){$('controls').append(button(label,()=>{message('');if(kind==='start'&&state.players.some(p=>!p.ready)){if(!confirm('還有孩子沒有準備好，要先開始嗎？'))return;more.force=true;}if(kind==='open'&&state.audioMode==='teacher'&&teacherAudioDone!==code+':'+state.index&&!confirm('老師端尚未播完題目，確定現在開始計時嗎？'))return;if(kind==='open'&&state.audioMode!=='teacher'&&state.players.some(p=>!p.heard)){if(!confirm('還有孩子沒有聽完，要開始計時嗎？'))return;more.force=true;}if(kind==='close'&&!confirm('確定結束這個測試房間嗎？'))return;send(kind,more);}));$('controls').lastChild.disabled=commands.hostPending()||socket?.readyState!==1;}
function render(){const s=state,key=s.code+':'+s.index;if(s.transport==='peer'){transport='peer';$('peer-status').hidden=false;document.querySelector('.notice').textContent='🖥️ P2P 教師電腦主機試玩・不發星星、不寫正式錯題紀錄；老師可下載 CSV。請保持電腦不休眠、主持頁不關閉。';}else $('peer-status').hidden=true;if(completion.render(s)){audio.pause();return;}document.body.classList.add('classroom-active');$('room-title').textContent=s.title;$('my-seat').textContent=host?'👩‍🏫 老師主持':seat+' 號';$('invite').hidden=!host||s.phase!=='lobby';$('student-link').href=s.authenticated?'https://j822925.github.io/zhuyin-game-new/classroom.html?class='+encodeURIComponent(s.classId):location.origin+'/trial/classroom.html?room='+s.code;if(host&&s.authenticated)$('invite').querySelector('p').textContent='孩子用原本主畫面圖示進遊戲、選座號並輸入密碼，再點「加入全班問答」，選本班活動即可。';
 $('phase-title').textContent=({lobby:'🌈 等大家加入',listening:'🔊 先聽題目，等老師開始',question:'✨ 選出你聽到的注音！',paused:'⏸️ 老師暫停中',reveal:'🌟 一起看正確答案',finished:'🏆 全班挑戰完成！',closed:'活動已結束'})[s.phase];$('progress').textContent=s.index<0?`已加入 ${s.players.length} 位，準備好 ${s.players.filter(p=>p.ready).length} 位`:`第 ${s.index+1} / ${s.total} 題・已作答 ${s.players.filter(p=>p.answered).length} / ${s.players.length} 位`;
 $('controls').replaceChildren();$('choices').replaceChildren();$('feedback').textContent='';$('ranking').replaceChildren();$('report').replaceChildren();$('audio-area').hidden=!s.question||['finished','closed'].includes(s.phase)||!host&&s.audioMode==='teacher';
 if(host){if(s.phase==='lobby')hostControl('🚀 大家好了，開始！','start');if(s.phase==='listening')hostControl('⏱️ 開始作答計時','open');if(s.phase==='question'){hostControl('✅ 揭曉答案','reveal');hostControl('⏸️ 暫停','pause');}if(s.phase==='paused')hostControl('▶️ 繼續','resume');if(s.phase==='reveal')hostControl(s.index===s.total-1?'🏆 查看總成績':'➡️ 下一題','next');if(s.phase!=='closed')hostControl('結束活動','close');if(transport==='peer'&&s.phase!=='finished'&&s.phase!=='closed')$('controls').append(button('🔗 重新開放 P2P 連線',()=>socket.reopen()));}
 else if(s.phase==='lobby') {const me=s.players.find(p=>p.seat===seat);if(!me?.ready){const b=button('🎧 下載聲音，準備好了！',prepare);b.id='prepare';b.disabled=preparing;b.textContent=preparing?`🎧 正在準備聲音 ${prepared}/${prepareTotal}`:'🎧 下載聲音，準備好了！';$('controls').append(b);}else $('feedback').textContent=s.audioMode==='teacher'?'🙌 已加入！題目由老師播放，不必下載聲音。':'🙌 準備好了！等老師開始。';}
 if(s.question&&!['finished','closed'].includes(s.phase))s.question.choices.forEach((value,i)=>{const b=el('button');b.append(el('span',['▲','●','◆','■'][i]),el('span',value));b.firstChild.className='shape';b.dataset.value=value;b.classList.toggle('selected',s.mine?.answer===value||pendingAnswer?.key===key&&pendingAnswer.value===value);b.classList.toggle('correct',s.phase==='reveal'&&s.question.answer===value);b.disabled=host||s.phase!=='question'||s.mine?.answer!==null||!!pendingAnswer&&pendingAnswer.key===key||socket?.readyState!==1;b.onclick=()=>{try{send('answer',{value});}catch(e){error(e);}};$('choices').append(b);});
 $('choices').classList.toggle('locked',s.phase==='listening'||s.phase==='paused');
 if(s.phase==='listening')$('feedback').textContent=host?'👉 下一步：按「開始作答計時」，孩子才可以選答案。':(s.audioMode==='teacher'?'👂 聽老師播放題目，等老師開始才能選答案。':'🔒 先聽題目，等老師開始才能選答案。');
 if(s.phase==='question'&&pendingAnswer?.key===key)$('feedback').textContent='📨 正在送出答案；網路慢會自動重送，請稍等。';
 if(s.mine?.answer!==null&&s.mine?.answer!==undefined&&s.phase==='question')$('feedback').textContent='🙌 已收到答案！等老師揭曉。';
 if(s.phase==='reveal'){$('feedback').textContent=(host?'正確答案：':s.mine?.correctAnswer?'🎉 答對了！正確答案：':'🌱 一起記住，正確答案：')+s.question.answer;if(!host)$('feedback').append(el('br'),el('span','本題 +'+(s.mine?.points||0)+' 分'));}
 if(s.phase==='finished'&&transport==='peer'&&host){$('report').append(el('p',socket?.synced?'✅ 試玩摘要已同步。星星與正式錯題紀錄不變。':'本場為 P2P 試玩，不發星星、不寫正式錯題紀錄。建議下載 CSV 留存。'));if(socket?.syncFailed)$('report').append(button('↻ 重傳試玩摘要',()=>socket.retryFinish()));}
 if(s.phase==='finished'){$('ranking').append(el('h2','🏆 前五名・掌聲鼓勵！'),rankTable(s.ranking));if(host){$('report').append(button('📥 下載本場成績 CSV',download));if(s.rewarding)$('report').append(el('p',s.rewardsPending?'⭐ 獎勵正在同步；即使關閉活動也會自動補發，請勿另開活動補發。':'⭐ 本場星星已完成結算。'));}else {$('feedback').textContent=`完成了！答對 ${s.mine?.correct||0} / ${s.total} 題。`;if(s.rewarding)$('feedback').append(el('br'),el('span',s.mine?.rewardPending?'⭐ 星星正在存入帳號，稍等一下！':s.mine?.rewardStars?'🎉 獲得 '+s.mine.rewardStars+' 顆星星，已存入帳號！':'本場沒有星星入帳，請老師確認帳號狀態。'));}}
 $('players').replaceChildren();if(host||s.phase==='lobby'){const list=el('div');list.className='players';for(const p of s.players){const row=el('div',`${p.seat} 號 ${!p.online?'・離線':s.phase==='lobby'?p.ready?'✅ 準備好':'🎧 準備中':p.answered?'✅ 已作答':s.audioMode==='teacher'?'👂 等老師播放':p.heard?'👂 聽完了':'🔊 聆聽中'}`);row.className='player'+(p.online?'':' offline');if(host&&s.phase==='lobby')row.append(button('移除',()=>{if(confirm('移除 '+p.seat+' 號，讓這個座號重新加入嗎？'))send('remove',{seat:p.seat});}));list.append(row);}$('players').append(list);}
 const rule=s.scoring==='speed'?'⚡ 答對越快，分數越高！每題最高 1000 分、最低 500 分；答錯或未答 0 分。':'🌱 不比速度，每題答對 1000 分。';$('room-note').textContent=rule+(host?' 先聽題，按開始作答才計時；暫停不扣時間。錯題會存到本班後台。'+(s.recordsPending?' ⚠ 錯題尚未同步，系統正在重試；後台請稍後重新查詢。':''):(s.audioMode==='teacher'?' 題目由老師統一播放，需要重聽請告訴老師。作答只能選一次。只公布前五名。':' 可以重播，作答只能選一次。只公布前五名。'));if(s.transport==='peer')$('room-note').textContent=rule+' 🖥️ 作答直接傳給老師電腦，遊戲中不傳給 Cloudflare。本場試玩不發星星、不寫正式錯題紀錄。';if(s.rewarding)$('room-note').append(el('br'),el('span','⭐ 活動完成：第 1～5 名 5 顆、第 6～10 名 2 顆、第 11 名起 1 顆；同分同獎勵，每場只領一次。'));
 if(audioKey!==key){audioKey=key;playGeneration++;audio.pause();$('audio-status').textContent='';window.scrollTo(0,0);if(s.question&&s.phase==='listening'&&(host||s.audioMode!=='teacher'))play();}if(s.mine?.answer!==null&&s.mine?.answer!==undefined)pendingAnswer=null;
 if(host&&s.audioMode==='teacher'&&s.phase==='lobby'&&teacherMediaCode!==s.code){teacherMediaCode=s.code;prepareTeacherAudio();}
 if(host&&s.phase==='lobby'&&preparing)$('feedback').textContent=`🎧 老師端正在準備題目聲音 ${prepared}/${prepareTotal}；孩子不必下載，可以先加入。`;
 if(host&&commands.hostPending())$('feedback').textContent=commands.control()?.kind==='start'?'📡 正在開始，請稍等；網路慢會自動重試。':'📡 正在更新，請稍等；不必重複按。';
}
function rankTable(rows){const wrap=el('div');wrap.className='table-wrap';const table=el('table'),head=el('tr');for(const t of ['名次','座號','答對題數','分數'])head.append(el('th',t));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');let rank=0,last=-1;rows.forEach((p,i)=>{if(p.score!==last)rank=i+1;last=p.score;const r=el('tr');if(rank===1)r.className='rank-first';for(const t of [rank,p.seat+' 號',p.correct,p.score])r.append(el('td',t));body.append(r);});table.append(body);wrap.append(table);return wrap;}
function download(){const totals=state.players.map(p=>{const answers=state.history.flatMap(h=>h.answers.filter(a=>a.seat===p.seat));return[p.seat,answers.filter(a=>a.correct).length,state.total,answers.reduce((n,a)=>n+(a.points??(a.correct?1000:0)),0)];});const rows=[['座號','答對題數','題數','分數'],...totals,[],['題號','正確答案','座號','作答','答對','本題分數','作答秒數']];for(const h of state.history)for(const a of h.answers)rows.push([h.index+1,h.target,a.seat,a.value||'未作答',a.correct?'是':'否',a.points??(a.correct?1000:0),a.responseMs===null||a.responseMs===undefined?'':(a.responseMs/1000).toFixed(2)]);const blob=new Blob(['\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=el('a');a.href=u;a.download='全班問答-'+new Date(Date.now()+28800000).toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('copy-link').onclick=async()=>{try{await navigator.clipboard.writeText($('student-link').href);message('已複製學生加入連結。');}catch{message('請長按或複製這個連結：'+$('student-link').href);}};$('reconnect').onclick=()=>{stopped=false;retry=0;connect().catch(error);};
setInterval(()=>{if(state?.phase==='question')$('timer').textContent='⏱️ '+Math.max(0,Math.ceil((state.deadline-Date.now()-offset)/1000))+' 秒';else $('timer').textContent='';},250);
document.addEventListener('visibilitychange',()=>{if(document.hidden){audio.pause();if(host&&state&&['question','listening'].includes(state.phase))try{send('pause');}catch{}}else if(code&&!stopped){if(socket?.readyState!==1){retry=0;connect().catch(()=>{});}else commands.sync();}});
window.addEventListener('pagehide',e=>{stopped=true;clearInterval(heartbeat);clearTimeout(reconnectTimer);clearTimeout(firstStateTimer);commands.stop();playGeneration++;audio.pause();if(!e.persisted)sounds.dispose();socket?.close();});
window.addEventListener('offline',()=>{$('connection').textContent='🟠 網路中斷，連上後會自動恢復';socket?.close();});
window.addEventListener('online',()=>{if(code&&!stopped)connect().catch(()=>{});});
window.addEventListener('pageshow',e=>{if(e.persisted){stopped=false;commands.start();if(code)connect().catch(()=>{});}});
async function studentRooms(){
 const entry=$('student-entry');entry.replaceChildren(el('h2','🎒 加入全班問答'));
 if(!studentIdentity){entry.append(el('p','先用平常的座號和密碼登入，就可以和同學一起答題囉！'));const link=el('a','🏡 回首頁登入');link.className='home';link.href=homeUrl;entry.append(link);return;}
 seat=studentIdentity.seat;entry.append(el('h3',seat+' 號，選老師開的活動吧！'));const list=el('div');list.className='activity-list';entry.append(list);const refresh=button('↻ 重新看看老師開好了沒',studentRooms);entry.append(refresh);message('');
 try{const [cloud,peer]=await Promise.all([api('/student-rooms',{device}).catch(e=>({rooms:[],failure:e})),api('/peer/student-rooms',{device}).catch(e=>({rooms:[],failure:e}))]);if(cloud.failure&&peer.failure)throw cloud.failure;const out={rooms:[...cloud.rooms,...peer.rooms]};if(!out.rooms.length)list.append(el('p','🌱 老師還沒有開活動。等老師開好，再按下面的重新讀取。'));if(cloud.failure||peer.failure)list.append(el('p','⚠ 部分活動暫時無法讀取；請確認老師開的活動是否出現，必要時重新讀取。'));
 for(const room of out.rooms){const b=button((room.transport==='peer'?'🖥️ P2P 試玩・':'🚀 ')+room.title+(room.phase==='lobby'?'・加入活動':'・回到活動'),async()=>{await unlock();transport=room.transport||'cloud';code=room.code;stopped=false;retry=0;await connect();});b.className='primary activity-join';list.append(b);}
 }catch(e){error(e);const link=el('a','🏡 回首頁');link.className='home';link.href=homeUrl;list.append(link);}
}
if(normal)await studentRooms();
