import {MONSTER_CONCEPTS} from './data/monster-concepts.js?v=20261003-concepts1';
const $=id=>document.getElementById(id),key='zhuyin.monster-concept-likes.20261003';let liked=new Set(),filter='all',selected=0;
try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))liked=new Set(saved.filter(id=>MONSTER_CONCEPTS.some(c=>c.id===id)));}catch{}
function toggle(id){liked.has(id)?liked.delete(id):liked.add(id);try{localStorage.setItem(key,JSON.stringify([...liked]));}catch{}render();if($('detail').open)renderDetail();}
function likeButton(c){const b=document.createElement('button');b.className='like';b.textContent=liked.has(c.id)?'♥ 已記下喜歡':'♡ 喜歡這個造型';b.setAttribute('aria-pressed',String(liked.has(c.id)));b.setAttribute('aria-label',(liked.has(c.id)?'取消喜歡':'喜歡')+c.name);b.onclick=()=>toggle(c.id);return b;}
function card(c,{detail=false}={}){const el=document.createElement(detail?'div':'button');if(!detail){el.type='button';el.setAttribute('aria-label','放大看'+c.name);el.onclick=()=>open(c.id);}el.className='concept-card frame-'+c.frame;el.style.setProperty('--color',c.color);el.style.setProperty('--accent',c.accent);
const label=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls;n.textContent=text;return n;};el.append(label('span','card-number',String(c.number).padStart(2,'0')),label('span','card-mark',c.mark),label('p','card-group',c.group));const stage=label('span','card-art',''),im=document.createElement('img');im.src=c.image;im.alt=c.name+'・'+c.group;im.loading=detail?'eager':'lazy';im.decoding='async';stage.append(im);el.append(stage,label('span','card-title',c.name),label('span','card-lore',c.line),label('span','card-bottom','造 型 提 案'));return el;}
function visible(){return MONSTER_CONCEPTS.filter(c=>filter==='all'||(filter==='liked'?liked.has(c.id):c.group===filter));}
function render(){const rows=visible();$('count').textContent=(filter==='liked'?'喜歡的造型':'本頁造型')+' · '+rows.length+' 位';$('gallery').replaceChildren(...rows.map(c=>{const wrap=document.createElement('article');wrap.className='card-wrap';wrap.append(card(c),likeButton(c));return wrap;}));$('empty').hidden=rows.length>0;for(const b of document.querySelectorAll('[data-filter]'))b.setAttribute('aria-pressed',String(b.dataset.filter===filter));}
function open(id){selected=MONSTER_CONCEPTS.findIndex(c=>c.id===id);renderDetail();$('detail').showModal();$('detail').scrollTop=0;}
function renderDetail(){const c=MONSTER_CONCEPTS[selected];$('detail-art').replaceChildren(card(c,{detail:true}));$('detail-kind').textContent=c.group+' · '+String(c.number).padStart(2,'0');$('detail-title').textContent=c.name;$('detail-lore').textContent=c.line;$('detail-position').textContent=(selected+1)+' / '+MONSTER_CONCEPTS.length;const b=$('detail-like');b.textContent=liked.has(c.id)?'♥ 已記下喜歡':'♡ 喜歡這個造型';b.setAttribute('aria-pressed',String(liked.has(c.id)));b.onclick=()=>toggle(c.id);}
for(const b of document.querySelectorAll('[data-filter]'))b.onclick=()=>{filter=b.dataset.filter;render();};$('close').onclick=()=>$('detail').close();$('previous').onclick=()=>{selected=(selected+MONSTER_CONCEPTS.length-1)%MONSTER_CONCEPTS.length;renderDetail();};$('next').onclick=()=>{selected=(selected+1)%MONSTER_CONCEPTS.length;renderDetail();};$('detail').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){$('previous').click();e.preventDefault();}if(e.key==='ArrowRight'){$('next').click();e.preventDefault();}});render();
