import {createApiClient} from './api-client.js?v=20260926-classes1';
import {createStudentAuth} from './student-auth.js?v=20260926-classes1';
const $=id=>document.getElementById(id),client=createApiClient('https://zhuyin-api.j822925.workers.dev/api');
let config=null,seat='',question=null,selection={},heard=false,busy=false,pending=null,after='';
const auth=createStudentAuth({demo:false,getConfig:()=>config,post:d=>client.post(d)}),audio=new Audio();audio.preload='auto';
const messages={authentication_required:'請再輸入密碼，就能接著複習。',review_changed:'這題有新的錯題紀錄，請重新打開錯題本。',review_unavailable:'這筆錯題已清理，請重新打開錯題本。'};
async function request(d){const out=await auth.request({...d,seat});if(out.error)throw Error(out.error);return out;}
function enable(){const ready=heard&&!busy&&!pending&&!!question;$('submit').disabled=!ready||!(question?.mode==='single'?selection.answer!==undefined:selection.initial!==undefined&&selection.final!==undefined);document.querySelectorAll('[data-choice]').forEach(b=>b.disabled=!ready);$('start').disabled=busy||!config;$('next').disabled=busy;$('mode').disabled=busy||!!pending;$('seat').disabled=busy||!!pending;}
async function run(fn){if(busy)return;busy=true;$('home-message').dataset.error='false';$('home-message').textContent='正在讀取／保存…';enable();try{await fn();$('home-message').textContent='';$('retry').hidden=true;}catch(e){$('home-message').dataset.error='true';$('home-message').textContent=messages[e.message]||'網路還沒確認，請按重新連線。答案不會因等待而變成答錯。';$('retry').hidden=false;if(['review_changed','review_unavailable'].includes(e.message))pending=null;}finally{busy=false;enable();}}
async function play(){try{audio.currentTime=0;await audio.play();heard=true;$('audio-status').textContent='仔細聽，想再聽幾次都可以。';enable();}catch{$('audio-status').textContent='請再點喇叭，並確認音量和網路。';}}
function options(id,values,kind){$(id).replaceChildren();for(const value of values){const b=document.createElement('button');b.type='button';b.textContent=value||'空白';b.dataset.choice=kind;b.onclick=()=>{selection[kind]=value;$(id).querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));if(kind!=='answer')$(kind+'-slot').textContent=value||'空白';enable();};$(id).append(b);}}
async function loadQuestion(){audio.pause();const out=await request({kind:'notebook-list',mode:$('mode').value,after});question=out.question;heard=false;selection={};$('feedback').hidden=true;$('empty').hidden=!!question;$('practice').hidden=!question;if(!question)return;$('count').textContent=`還有 ${out.count} 種聲音等你複習`;$('mode-label').textContent=question.mode==='single'?'👂 聽音辨識':'🧩 拼音工坊';$('choices').hidden=question.mode!=='single';$('spelling').hidden=question.mode!=='spelling';if(question.mode==='single')options('choices',question.choices,'answer');else{for(const kind of ['initial','final']){$(kind+'-slot').textContent='';options(kind+'-choices',question.choices[kind],kind);}$('tone').textContent=question.toneMark;$('tone').parentElement.dataset.neutral=String(question.toneMark==='˙');}audio.src=question.audio;$('audio-status').textContent='請點喇叭聽題目';enable();await play();}
async function sendPending(){const out=await request(pending);pending=null;after=question.target;$('practice').hidden=true;$('feedback').hidden=false;$('feedback-icon').textContent=out.correct?'🌟':'🌱';$('feedback-title').textContent=out.correct?'答對了！這題畢業囉！':'再聽一次，我們慢慢練';$('correct-answer').textContent=out.answer;$('replay').hidden=out.correct;audio.src=out.audio;if(!out.correct)await play();}
async function open(){const selected=$('seat').value;if(!selected){$('home-message').textContent='先選自己的座號喔！';return;}if(seat!==selected){auth.forgetAll();after='';}seat=selected;if(!await auth.ensure(seat))return;auth.setPrimary(seat);await loadQuestion();}
$('start').onclick=()=>run(open);$('listen').onclick=$('replay').onclick=play;$('next').onclick=()=>run(loadQuestion);
$('submit').onclick=()=>{if($('submit').disabled)return;pending={kind:'notebook-answer',mode:question.mode,target:question.target,revision:question.revision,answer:question.mode==='single'?selection.answer:selection.initial+selection.final};run(sendPending);};
$('retry').onclick=()=>run(async()=>{if(!await auth.ensure(seat))return;auth.setPrimary(seat);if(pending)await sendPending();else await loadQuestion();});
window.addEventListener('pagehide',()=>audio.pause());
client.get({api:'config'}).then(c=>{config=c;for(const s of c.seats)$('seat').append(new Option(s+' 號',s));seat=auth.currentSeat();if(seat)$('seat').value=seat;enable();if(seat)run(open);}).catch(()=>{$('home-message').textContent='還沒讀到座號，請確認網路後重新整理。';});
