import {CHARACTERS,STARTERS,portrait} from './characters.js?v=20260913-heroes1';
import {STAR_CARDS} from './data/star-cards.js?v=20260919-star1';
export const PROFILE_CHARACTERS=[...CHARACTERS,...STAR_CARDS.map(c=>({...c,emoji:'✨',name:c.symbol+'之星使・'+c.name}))];
const $=id=>document.getElementById(id);
export function createStudentProfile({demo,auth,getSeat,getSeats,getOwned,getAvatar,onChange,isHome=()=>true}){
 const cache=new Map();let version=0,openedSeat='',draftAvatar='',busy=false,loaded=false;
 const button=document.createElement('button');button.id='open-profile';button.type='button';button.setAttribute('aria-haspopup','dialog');
 document.querySelector('.top-actions').prepend(button);
 const dialog=document.createElement('dialog');dialog.id='profile-dialog';dialog.setAttribute('aria-labelledby','profile-title');
 dialog.innerHTML='<div class="profile-top"><h2 id="profile-title">我的角色</h2><button id="profile-close" type="button" aria-label="關閉我的角色">✕</button></div><p id="profile-seat"></p><div class="profile-preview" id="profile-preview"></div><p id="profile-character-name"></p><form id="profile-form"><label for="profile-nickname">角色名稱（最多 12 個字）</label><input id="profile-nickname" autocomplete="off" placeholder="幫自己取個冒險名字"><p class="profile-hint">可以用中文、英文、數字；留白就使用原本名字。老師仍看得到你的真實姓名。</p><h3>選擇我的角色</h3><div id="profile-choices"></div><p id="profile-message" role="status" aria-live="polite"></p><button id="profile-save" type="submit">儲存我的角色</button><button id="profile-reload" type="button">重新讀取</button></form>';
 document.body.append(dialog);
 function character(id){return PROFILE_CHARACTERS.find(c=>c.id===id)||CHARACTERS[0];}
 function identity(seat){const p=auth.verified(seat)?cache.get(seat):null;return {seat,name:p?.nickname||p?.name||seat+' 號',character:p?character(p.avatar):getAvatar(seat)};}
 function renderHeader(){const seat=getSeat(),person=seat&&auth.verified(seat)?identity(seat):null;button.replaceChildren();const face=document.createElement('span');face.className='profile-head';face.innerHTML=portrait(person?.character||CHARACTERS[0]);const name=document.createElement('span');name.className='profile-header-name';name.textContent=person?person.name:'我的角色';button.append(face,name);button.setAttribute('aria-label',person?`${seat} 號 ${person.name}，開啟我的角色`:'我的角色，請先選座號登入');button.disabled=!isHome();}
 function remember(p){cache.set(p.seat,p);renderHeader();onChange?.();return p;}
 async function fetchProfile(seat){
  if(demo){let old;try{old=JSON.parse(localStorage.getItem('zhuyin.demo.profile.'+seat)||'null');}catch{}return {seat,name:'',nickname:old?.nickname||'',avatar:old?.avatar||getAvatar(seat).id,owned:getOwned(seat)||STARTERS,revision:old?.revision||0};}
  const p=await auth.request({kind:'profile',seat});if(p.error)throw Error(p.error);
  // Preserve the previous device-only avatar until the first explicit profile save.
  if(!p.revision){try{const previous=localStorage.getItem('zhuyin.avatar.'+seat),id=previous&&JSON.parse(previous);if(p.owned.includes(id))p.avatar=id;}catch{}}
  return p;
 }
 async function refresh(){const v=version;await Promise.all(getSeats().filter(s=>s&&auth.verified(s)).map(async seat=>{try{const p=await fetchProfile(seat);if(v===version&&auth.verified(seat))remember(p);}catch{}}));renderHeader();}
 function preview(){const c=character(draftAvatar);$('profile-preview').innerHTML=portrait(c);$('profile-character-name').textContent=c.name;for(const b of dialog.querySelectorAll('[data-profile-avatar]'))b.setAttribute('aria-pressed',String(b.dataset.profileAvatar===draftAvatar));}
 function draw(p){$('profile-seat').textContent=`${p.seat} 號${p.name?'・'+p.name:''}`;$('profile-nickname').value=p.nickname;draftAvatar=p.avatar;$('profile-choices').replaceChildren();for(const id of p.owned){const c=PROFILE_CHARACTERS.find(c=>c.id===id);if(!c)continue;const b=document.createElement('button');b.type='button';b.dataset.profileAvatar=id;b.setAttribute('aria-label','選擇'+c.name);b.innerHTML=portrait(c,'character-portrait','lazy');const name=document.createElement('span');name.textContent=c.name;b.append(name);b.onclick=()=>{draftAvatar=id;preview();};$('profile-choices').append(b);}preview();}
 function lock(on){busy=on;for(const el of dialog.querySelectorAll('button,input'))el.disabled=on;$('profile-save').disabled=on||!loaded;}
 const messages={invalid_profile:'名字最多 12 個字，請使用中文、英文、數字、空格或短橫線。',avatar_not_owned:'這個角色尚未取得，請重新讀取收藏。',stale_profile:'另一台裝置已更換角色，請重新讀取後再選擇。',authentication_required:'登入已過期，請關閉此視窗後重新登入。'};
 async function open(){const seat=getSeat();if(!seat){$('seat')?.focus();$('home-message')&&($('home-message').textContent='請先選擇座號，再點自己的頭貼。');return;}if(!await auth.ensure(seat))return;openedSeat=seat;loaded=false;draftAvatar='';const v=++version;dialog.showModal();dialog.scrollTop=0;$('profile-message').textContent='正在讀取你的角色…';$('profile-preview').replaceChildren();$('profile-character-name').textContent='';$('profile-seat').textContent=seat+' 號';$('profile-choices').replaceChildren();$('profile-nickname').value='';lock(true);try{const p=await fetchProfile(seat);if(v!==version)return;remember(p);draw(p);loaded=true;$('profile-message').textContent='';}catch(e){if(v===version)$('profile-message').textContent=messages[e.message]||'角色讀取失敗，請按重新讀取。';}finally{if(v===version)lock(false);}}
 button.onclick=open;
 $('profile-reload').onclick=()=>{dialog.close();open();};
 $('profile-close').onclick=()=>{if(!busy){version++;dialog.close();}};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();else version++;});
 $('profile-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const p=cache.get(openedSeat);if(!p||!auth.verified(openedSeat)){$('profile-message').textContent='請先重新登入並讀取角色。';return;}const nickname=$('profile-nickname').value.normalize('NFKC').trim();if([...nickname].length>12||(nickname&&!/^[\p{L}\p{N} ·\-]+$/u.test(nickname))){$('profile-message').textContent=messages.invalid_profile;return;}lock(true);const v=version;$('profile-message').textContent='儲存中…';try{let out;if(demo){out={...p,nickname,avatar:draftAvatar,revision:p.revision+1};localStorage.setItem('zhuyin.demo.profile.'+openedSeat,JSON.stringify(out));}else{out=await auth.request({kind:'profile-save',seat:openedSeat,nickname,avatar:draftAvatar,revision:p.revision});if(out.error)throw Error(out.error);}if(v!==version)return;remember(out);draw(out);$('profile-message').textContent='已儲存！回到遊戲就會使用這個名字和角色。';}catch(e){if(v===version)$('profile-message').textContent=messages[e.message]||'尚未確認儲存結果，請按重新讀取確認。';}finally{if(v===version)lock(false);}};
 renderHeader();
 return {identity,refresh,renderHeader,clearSeat(seat){version++;cache.delete(seat);if(openedSeat===seat){loaded=false;dialog.close();$('profile-nickname').value='';$('profile-preview').replaceChildren();$('profile-choices').replaceChildren();}renderHeader();},renderPlayer(root,seat){const p=identity(seat);root.replaceChildren();const image=document.createElement('span');image.className='playing-character';image.innerHTML=portrait(p.character);const label=document.createElement('strong');label.textContent=`${seat} 號・${p.name}`;root.classList.add('profile-playing');root.append(image,label);}};
}
