import test from 'node:test';import assert from 'node:assert/strict';import {existsSync,readFileSync} from 'node:fs';
import {MONSTERS} from '../data/monsters.js';import {PACKED_BATTLES,PACKED_BATTLE_VERSION} from '../data/packed-battle-frames.js';import {loadPackedBattle} from '../battle-frame-loader.js';
test('battle pages also refresh the stylesheet importing the enemy presentation',()=>{const read=f=>readFileSync(new URL('../'+f,import.meta.url),'utf8');for(const file of ['index.html','grade2.html','exam.html','online.html','reading.html','motion-preview.html'])assert(read(file).includes('character-motion.css?v='+PACKED_BATTLE_VERSION),file);assert(read('character-motion.css').includes('battle-rpg.css?v='+PACKED_BATTLE_VERSION));});
test('every encounter has precut poses with the reviewed body scale and complete bounds',()=>{
 assert.equal(Object.keys(PACKED_BATTLES).length,MONSTERS.length);
 for(const monster of MONSTERS){const p=PACKED_BATTLES[monster.id];assert(existsSync(new URL('../'+p.atlas,import.meta.url)));assert.equal(p.frames.length,monster.theme==='concept'?12:8);assert(p.sourceScale>0&&p.sourceScale<=1);for(const f of p.frames){const [x,y,w,h]=f.rect;assert(x>=0&&y>=0&&x+w<=p.width&&y+h<=p.height);assert(f.pivot.every(Number.isFinite)&&f.scale>0&&f.bodyRatio>0);}}
});
function environment(t,behavior){const prior={Image:globalThis.Image,document:globalThis.document},requests=[],draws=[];globalThis.Image=class {set src(url){this.url=url;if(!url)return;requests.push(url);const result=behavior(requests.length);if(result==='stall')return;queueMicrotask(()=>{if(result==='error'){this.onerror?.();return;}const p=PACKED_BATTLES['ink-book-spirit'];this.naturalWidth=result==='wrong'?1:p.width;this.naturalHeight=p.height;this.onload?.();});}};globalThis.document={createElement:()=>({getContext:()=>({drawImage:(...args)=>draws.push(args)})})};t.after(()=>{for(const key of Object.keys(prior))if(prior[key]===undefined)delete globalThis[key];else globalThis[key]=prior[key];});return {requests,draws};}
test('normal loading only copies precut rectangles without reading full-size pixels',async t=>{const e=environment(t,()=> 'ok'),p=await loadPackedBattle('ink-book-spirit');assert.equal(e.requests.length,1);assert.equal(p.frames.length,12);assert.equal(e.draws.length,12);assert.deepEqual(p.frames[3].pivot,PACKED_BATTLES['ink-book-spirit'].frames[3].pivot);});
for(const fault of ['error','wrong'])test('a '+fault+' cached image retries with a fresh URL',async t=>{const e=environment(t,n=>n===1?fault:'ok');assert.equal((await loadPackedBattle('ink-book-spirit')).frames.length,12);assert.equal(e.requests.length,2);assert(new URL(e.requests[1]).searchParams.has('retry'));assert.notEqual(e.requests[0],e.requests[1]);});
test('stalled requests finish with a bounded failure rather than swaying forever',async t=>{const e=environment(t,()=> 'stall');await assert.rejects(loadPackedBattle('ink-book-spirit',{timeout:5}),/timed out/);assert.equal(e.requests.length,2);});
test('characters without a prepared pack retain their original authored loader',async()=>{assert.equal(await loadPackedBattle('knight'),null);});
