import test from 'node:test';import assert from 'node:assert/strict';
import {MONSTERS} from '../data/monsters.js';import {monsterProgress,monsterLevel,monsterRequirements} from '../data/monster-collection-rules.js';import {startDemoMonster,creditDemoMonster,demoMonsters} from '../monster-cards-ui.js';
test('32 new villains require three learning levels; original four retain cumulative wins',()=>{for(const c of MONSTERS){assert.equal(monsterRequirements(c).length,c.theme==='concept'?3:0);}assert.equal(monsterLevel('compound'),monsterLevel('single'));assert.equal(monsterLevel('exam'),null);assert.equal(monsterLevel('turn'),null);assert.equal(monsterProgress(MONSTERS[4],{victories:30,level_mask:1}).monsterWins,1);assert.equal(monsterProgress(MONSTERS[0],{victories:3}).monsterWins,3);});
test('future tone condition keeps earned cards and requires a fourth distinct level',()=>{const c=MONSTERS[4];assert.equal(monsterProgress(c,{level_mask:7},{tone:true}).monsterRequiredWins,4);assert.equal(monsterProgress(c,{level_mask:7},{tone:true}).monsterWins,3);assert.equal(monsterProgress(c,{acquired:123,level_mask:1},{tone:true}).monsterCollected,true);assert.equal(monsterProgress(c,{level_mask:15},{tone:true}).monsterWins,4);});
test('demo: repeated listening and wrong rounds cannot unlock; receipts and persisted progress agree',()=>{
 const storage=new Map(),oldStorage=globalThis.localStorage,original=crypto.getRandomValues.bind(crypto);globalThis.localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};crypto.getRandomValues=a=>{a[0]=4;return a;};
 try{const modes=['single','single','compound','spelling','spelling','reading'],scores=[true,true,true,false,true,true],wins=[1,1,1,1,2,3];for(let i=0;i<modes.length;i++){const id='demo-fixture-round-'+i,encounter=startDemoMonster('901',id,modes[i]);assert.equal(encounter.monsterId,MONSTERS[4].id);const award=creditDemoMonster('901',id,scores[i],modes[i]);assert.equal(award.monsterWins,wins[i]);assert.equal(!!award.monsterCard,i===5);assert.deepEqual(creditDemoMonster('901',id,scores[i],modes[i]),award);assert.equal(demoMonsters('901').owned.length,i===5?1:0);}assert.equal(demoMonsters('901').progress[0].level_mask,7);
 const key='demo-fixture-conflict';startDemoMonster('901',key,'single');assert.throws(()=>creditDemoMonster('901',key,true,'spelling'),/encounter_level_conflict/);
 }finally{globalThis.localStorage=oldStorage;crypto.getRandomValues=original;}
});
