import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import {cacheName,publicMedia,orderedCards,MAX_ITEMS,MAX_BYTES,MAX_FILE,TTL} from '../cache-policy.js';
function fixture(){const events={},entries=new Map(),pending=[],calls=[];let offline=false,denied=false;
const key=r=>typeof r==='string'?r:r.url,cache={match:async r=>entries.get(key(r))?.clone(),put:async(k,r)=>{if(denied)throw Error('quota');entries.set(key(k),r.clone());},keys:async()=>[...entries.keys()].map(p=>new Request(p)),delete:async r=>entries.delete(key(r))};
const sandbox={URL,Request,Response,Headers,AbortController,setTimeout,clearTimeout,Date,cacheName,publicMedia,MAX_ITEMS,MAX_BYTES,MAX_FILE,TTL,caches:{open:async()=>cache,delete:async()=>true},self:{location:{href:'https://test.example/trial/media-worker.js'},addEventListener:(k,f)=>events[k]=f,skipWaiting:async()=>{},clients:{claim:async()=>{}}},fetch:async r=>{calls.push(r.url);if(offline)throw Error('offline');return new Response(Uint8Array.from([0,1,2,3,4,5,6,7]),{headers:{'content-type':'audio/mpeg'}});}};
vm.runInNewContext(fs.readFileSync(new URL('../media-worker.js',import.meta.url),'utf8').replace(/^import[^\n]+\n/,''),sandbox);
return {entries,calls,offline(v){offline=v;},denied(v){denied=v;},async get(path,options){let p;events.fetch({request:new Request('https://test.example'+path,options),respondWith:x=>p=x,waitUntil:x=>pending.push(x)});const r=await p;await Promise.all(pending.splice(0));return r;}};}
test('public-only allowlist excludes APIs, names, tokens, foreign origins and path traversal',()=>{for(const p of ['api','admin/api','data/answers.json','audio/../api','https://else.example/trial/audio/a.mp3','../audio/a.mp3'])assert.equal(publicMedia(p,'https://test.example/trial/'),false);assert(publicMedia('assets/a.webp?v=2','https://test.example/trial/'));});
test('cache hit, same-file deduplication, iPad range request and offline replay',async()=>{const f=fixture();await Promise.all([f.get('/trial/audio/a.mp3'),f.get('/trial/audio/a.mp3')]);assert.equal(f.calls.length,1);f.offline(true);const r=await f.get('/trial/audio/a.mp3',{headers:{Range:'bytes=2-4'}});assert.equal(r.status,206);assert.deepEqual([...new Uint8Array(await r.arrayBuffer())],[2,3,4]);assert.equal(f.calls.length,1);assert.equal((await f.get('/trial/audio/a.mp3',{headers:{Range:'bytes=99-'}})).status,416);});
test('bounded cache, per-version isolation, and denied storage never block successful network response',async()=>{const f=fixture();for(let i=0;i<MAX_ITEMS+3;i++)await f.get('/trial/audio/'+i+'.mp3');assert.equal(f.entries.size,MAX_ITEMS);assert(!f.entries.has('https://test.example/trial/audio/0.mp3'));await f.get('/trial/audio/new.mp3?v=1');await f.get('/trial/audio/new.mp3?v=2');assert(f.entries.has('https://test.example/trial/audio/new.mp3?v=1'));f.denied(true);assert.equal((await f.get('/trial/audio/quota.mp3')).status,200);});
test('private/API/code requests are not intercepted',async()=>{const f=fixture();for(const p of ['/trial/api','/trial/exam.html','/trial/exam.js','/audio/a.mp3'])assert.equal(await f.get(p),undefined);assert.equal(await f.get('/trial/audio/a.mp3',{method:'POST',body:'secret'}),undefined);assert.equal(f.calls.length,0);});
test('card order follows zhuyin and skips unpublished symbols without mutating input',()=>{const cards=[{symbol:'ㄖ'},{symbol:'ㄆ'},{symbol:'ㄅ'},{symbol:'未知'}],copy=structuredClone(cards);assert.deepEqual(orderedCards(cards).map(c=>c.symbol),['ㄅ','ㄆ','ㄖ']);assert.deepEqual(cards,copy);});
